:github-address: https://github.com/hazelcast-guides/kubernetes
:templates-url: templates:ROOT:page$/
:hazelcast: Hazelcast IMDG
:framework: Kubernetes

= Hazelcast for Kubernetes

This sample is a guideline on how to start and use Hazelcast cluster in Kubernetes.

include::{templates-url}/link-to-repo.adoc[]

== What You’ll Learn

In this guide you will deploy Hazelcast cluster to Kubernetes and use it with Hazelcast client.

== Prerequisites

* Up and running https://kubernetes.io/[Kubernetes] cluster (version 1.9 or higher)
* Kubernetes command line tool, https://kubernetes.io/docs/tasks/tools/install-kubectl/[kubectl]
* (Recommended) https://helm.sh/docs/intro/install/[Helm CLI]

== Deploy Hazelcast cluster

There are different ways of deploying Hazelcast to Kubernetes. For the production environment we recommend Helm or Hazelcast Operator, because these methods provide the complete Hazelcast experience:

* Install Hazelcast Management Center at the same time
* Configure `livenessProbe` and `readinessProbe`
* Simple updates of Hazelcast configuration
* Enable rolling upgrades without data loss
* Automatic RBAC configuration
* Other useful features

[tabs]
====

Helm::
+
--
[source, bash]
----
helm repo add hazelcast https://hazelcast-charts.s3.amazonaws.com/
helm repo update
helm install hz-hazelcast hazelcast/hazelcast
----
--

Hazelcast Operator::
+

--
[source, bash]
----
kubectl apply -f https://raw.githubusercontent.com/hazelcast/hazelcast-operator/master/hazelcast-operator/operator-rbac.yaml
kubectl apply -f https://raw.githubusercontent.com/hazelcast/hazelcast-operator/master/hazelcast-operator/hazelcast-rbac.yaml
kubectl apply -f https://raw.githubusercontent.com/hazelcast/hazelcast-operator/master/hazelcast-operator/hazelcastcluster.crd.yaml
kubectl --validate=false apply -f https://raw.githubusercontent.com/hazelcast/hazelcast-operator/master/hazelcast-operator/operator.yaml
kubectl apply -f https://raw.githubusercontent.com/hazelcast/hazelcast-operator/master/hazelcast-operator/hazelcast.yaml
----
--

Kubectl::
+

--
[source, bash]
----
kubectl apply -f https://raw.githubusercontent.com/hazelcast/hazelcast-kubernetes/master/rbac.yaml

kubectl run hz-hazelcast-0 --image=hazelcast/hazelcast:$HAZELCAST_VERSION -l "role=hazelcast"
kubectl run hz-hazelcast-1 --image=hazelcast/hazelcast:$HAZELCAST_VERSION -l "role=hazelcast"
kubectl run hz-hazelcast-2 --image=hazelcast/hazelcast:$HAZELCAST_VERSION -l "role=hazelcast"

kubectl create service clusterip hz-hazelcast --tcp=5701 -o yaml --dry-run=client | kubectl set selector --local -f - "role=hazelcast" -o yaml | kubectl create -f -
----
--

====

You can check that the Hazelcast cluster is up and running.

[source, bash]
----
kubectl logs hz-hazelcast-0
...
Members {size:3, ver:3} [
        Member [10.216.6.7]:5701 - 6d2100e0-8dcf-4e7c-ab40-8e98e23475e3 this
        Member [10.216.5.6]:5701 - 5ab4d554-fd7d-4929-8475-0ddf79a21076
        Member [10.216.8.6]:5701 - 7f7dd5f4-e732-4575-89d6-a6e823da38da
]
----

== Configure Hazelcast client

First, you need to configure install Hazelcast client dependency.

[tabs]
====

Java::
+
--
.pom.xml
[source, xml]
----
<dependency>
    <groupId>com.hazelcast</groupId>
    <artifactId>hazelcast</artifactId>
    <version>${hazelcast.version}</version>
</dependency>
----
--

NodeJS::
+
--
[source, bash]
----
npm install hazelcast-client
----
--

====

Then, you can use Hazelcast client in your application code by configuring Hazelcast Kubernetes service `hz-hazelcast` as the server address.

[tabs]
====

Java::
+
--
[source, java]
----
ClientConfig config = new ClientConfig();
config.getConnectionStrategyConfig().getConnectionRetryConfig().setClusterConnectTimeoutMillis(Long.MAX_VALUE);
config.getNetworkConfig().addAddress("hz-hazelcast");
----
--

NodeJS::
+
--
[source, nodejs]
----
var clientConfig = {
    network: {
        clusterMembers: [
            'hz-hazelcast'
        ]
    }
}
const client = await Client.newHazelcastClient(clientConfig);
----
--

====

== Deploy Hazelcast client application

[tabs]
====

Java::
+
--
[source, bash]
----
mvn package -f java/pom.xml
docker build -t hazelcastguides/hazelcast-client java
----
--

NodeJS::
+
--
[source, nodejs]
----
docker build -t hazelcastguides/hazelcast-client nodejs
----
--

====

[NOTE]
====
If you use a remote Kubernetes cluster and you want to build your own image, then make sure that you push the Docker image into the Docker registry.
====

----
kubectl run hazelcast-client --image=hazelcastguides/hazelcast-client
----

----
kubectl logs hazelcast-client
...
Members {size:3, ver:3} [
        Member [10.216.6.7]:5701 - 6d2100e0-8dcf-4e7c-ab40-8e98e23475e3 this
        Member [10.216.5.6]:5701 - 5ab4d554-fd7d-4929-8475-0ddf79a21076
        Member [10.216.8.6]:5701 - 7f7dd5f4-e732-4575-89d6-a6e823da38da
]
...
Connection Successful!
Now the map named 'map' will be filled with random entries.
Current map size: 71754
Current map size: 71758
Current map size: 71782
Current map size: 71792
...
----

Execute the following command to remove the client.

----
kubectl delete pod hazelcast-client
----

== Clean up

[tabs]
====

Helm::
+
--
[source, bash]
----
helm uninstall hazelcast
----
--

Hazelcast Operator::
+

--
[source, bash]
----
kubectl delete -f https://raw.githubusercontent.com/hazelcast/hazelcast-operator/master/hazelcast-operator/hazelcast.yaml
kubectl delete -f https://raw.githubusercontent.com/hazelcast/hazelcast-operator/master/hazelcast-operator/operator.yaml
kubectl delete -f https://raw.githubusercontent.com/hazelcast/hazelcast-operator/master/hazelcast-operator/hazelcastcluster.crd.yaml
kubectl delete -f https://raw.githubusercontent.com/hazelcast/hazelcast-operator/master/hazelcast-operator/hazelcast-rbac.yaml
kubectl delete -f https://raw.githubusercontent.com/hazelcast/hazelcast-operator/master/hazelcast-operator/operator-rbac.yaml
----
--

Kubectl::
+

--
[source, bash]
----
kubectl delete service hz-hazelcast
kubectl delete pod hz-hazelcast-0 hz-hazelcast-1 hz-hazelcast-2
kubectl delete -f https://raw.githubusercontent.com/hazelcast/hazelcast-kubernetes/master/rbac.yaml
----
--
====

== Summary

This guide shows the basic setup for Hazelcast cluster for Kubernetes and use it with different clients.

== See Also
- xref:kubernetes-hpa:ROOT:index.adoc[Kubernetes HPA for Hazelcast cluster]
- xref:kubernetes-external-client:ROOT:index.adoc[External Hazelcast Client on Kubernetes]
- xref:kubernetes-sidecar:ROOT:index.adoc[Hazelcast as Sidecar container]
